### ISSUE TITLE
Number of followers maxes out at 30

### ISSUE THREAD

**Issue by rohittp0** [nikiljos/shn-github-api#2]
Try using this GitHub id gautamkrishnar . The problem is pagination.

**Comment by nikiljos** [comment]
I have noticed that but I thought that was some sort of maximum limit with the API, But now after searching a bit I came to find more with `page` param.... An interesting task for me... Thanks😀

**Comment by nikiljos** [comment]
Fixed in a7a7bcf24812dcabc9cfcf250cd4173f2b48ca88
